/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    textColor: (theme) => ({
      ...theme('colors'),
      primary: '#007fab',
      navFont: '#ffc37d',
      titleColor: '#FF5136',
      SecondaryDark: '#A46039',
    }),
    backgroundColor: (theme) => ({
      ...theme('colors'),
      primary: '#007fab',
      secondary: '#ffc37d',
      navBg: '#007FAB',
      titleColor: '#FF5136',
      SecondaryDark: '#A46039',
    }),
    borderColor: (theme) => ({
      ...theme('colors'),
      primary: '#007fab',
      secondary: '#ffc37d',
      navBg: '#007FAB',
      titleColor: '#FF5136',
      SecondaryDark: '#A46039',
    }),
    fontSize: {
      xs: '.75rem',
      sm: '.875rem',
      tiny: '.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '3.75rem',
      '7xl': '5rem',
      title: ['32px', '56px'],
    },

    extend: {
      fontFamily: {
        GenJyuuGothic: ['GenJyuuGothic', 'sans-serif'],
      },
      height: {
        110: '27rem',
      },
      backgroundSize: {
        55: '50rem',
        'start-size': '1430px',
        'menu-size': '60px',
        hand: '56px 69px',
        75: '75% 100%',
        100: '100% 100%',
      },
      backgroundImage: {
        'nav-bg': "url('../src/assets/bg/bg_menuSide.png')",
        'nav-close-btn': "url('../src/assets/btn/btn_burger_close.png')",
        'nav-open-btn': "url('../src/assets/btn/btn_burger_open.png')",
        'nav-close-btn-h': "url('../src/assets/btn/btn_burger_close_h.png')",
        'nav-open-btn-h': "url('../src/assets/btn/btn_burger_open_h.png')",
        'start-bg': "url('../src/assets/main/start.png')",
        'user-icon': "url('../src/assets/ic/ic_users.svg')",
        'ready-frame': "url('../src/assets/main/ready_frame.png')",
        'menu-info': "url('../src/assets/ic/ic_menu_info.png')",
        'menu-info-h': "url('../src/assets/ic/ic_menu_info_h.png')",
        'menu-list': "url('../src/assets/ic/ic_menu_list.png')",
        'menu-list-h': "url('../src/assets/ic/ic_menu_list_h.png')",
        'menu-strategy-h': "url('../src/assets/ic/ic_menu_strategy_h.png')",
        'menu-strategy': "url('../src/assets/ic/ic_menu_strategy.png')",
        'menu-job-h': "url('../src/assets/ic/ic_menu_job_h.png')",
        'menu-job': "url('../src/assets/ic/ic_menu_job.png')",
        'btn-user': "url('../src/assets/btn/btn_user.png')",
        'btn-user-h': "url('../src/assets/btn/btn_user_h.png')",
        'map-bg': "url('../src/assets/main/map.svg')",
        'btn-join': "url('../src/assets/btn/btn_join.png')",
        'btn-join-h': "url('../src/assets/btn/btn_join_h.png')",
        'btn-join-hand': "url('../src/assets/btn/btn_joinHand.gif')",
        'bg-talking': "url('../src/assets/bg/bg_talking.png')",
      },
      lineHeight: {
        40: '40px',
      },
      inset: {
        '1/8': '12.5%',
        26: '6.5rem',
        42: '10.75rem',
      },
      cursor: {
        default: 'url(../src/assets/cursor/cursor.png), default',
        pointer: 'url(../src/assets/cursor/cursor.png), pointer',
      },
    },
  },
  plugins: [],
};
